branch-defaults:
  bugfix/admin-dash:
    environment: Kira-api-env
  feature/prod:
    environment: Kira-api-env
    group_suffix: null
environment-defaults:
  Kira-api-env:
    branch: null
    repository: null
  kira-backend-production-env:
    branch: null
    repository: null
global:
  application_name: kira-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
